# Generated by Django 4.0.5 on 2022-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=200, null=True)),
                ('SOW', models.TextField(max_length=200, null=True)),
                ('Start_date', models.DateField(max_length=200, null=True)),
                ('End_date', models.DateField(auto_now_add=True, null=True)),
                ('Value', models.CharField(max_length=200, null=True)),
                ('customer', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Contract_No', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
