# Generated by Django 4.0.5 on 2022-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='SOW',
            field=models.TextField(),
        ),
    ]
