# Generated by Django 4.0.5 on 2022-07-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projects_sow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='End_date',
            field=models.DateField(null=True),
        ),
    ]
