# Generated by Django 4.0.5 on 2022-07-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projects_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='status',
        ),
    ]
