# Generated by Django 4.0.5 on 2022-07-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projects_contract_no1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Contract_No1',
        ),
    ]
