# Generated by Django 4.0.5 on 2022-07-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_projects_contract_no1'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
