# Generated by Django 4.0.5 on 2022-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_projects_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Project_Manager',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
