# Generated by Django 4.0.5 on 2022-07-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_projects_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='End_User_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='End_User_Name_Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='End_User_Name_Tel',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
