# Generated by Django 4.0.5 on 2022-07-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_projects_end_user_name_projects_end_user_name_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='End_User_Name',
            new_name='End_User_Contact',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='End_User_Name_Email',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='End_User_Name_Tel',
        ),
    ]
