# Generated by Django 4.0.5 on 2022-07-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_rename_end_user_name_projects_end_user_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid_name', models.CharField(max_length=200, null=True)),
                ('Reference_number', models.CharField(max_length=200, null=True)),
                ('End_user', models.CharField(max_length=200, null=True)),
                ('work_category', models.CharField(max_length=200, null=True)),
                ('Last_date_inquiries', models.DateTimeField(max_length=200, null=True)),
                ('Deadline', models.DateTimeField(max_length=200, null=True)),
                ('Bid_opening_date', models.DateTimeField(max_length=200, null=True)),
                ('Bid_value', models.FloatField(max_length=200, null=True)),
                ('Are_you_Interest', models.BooleanField(max_length=200, null=True)),
                ('Did_you_bought', models.BooleanField(max_length=200, null=True)),
                ('File_downloaded', models.BooleanField(max_length=200, null=True)),
            ],
        ),
    ]
