# Generated by Django 4.0.5 on 2022-07-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='Failed_To_Submit',
            field=models.BooleanField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='WIN',
            field=models.BooleanField(max_length=200, null=True),
        ),
    ]
