# Generated by Django 4.0.5 on 2022-07-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_bids_failed_to_submit_bids_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_no', models.CharField(max_length=200, null=True)),
                ('Item_name', models.CharField(max_length=200, null=True)),
                ('Unit', models.CharField(max_length=200, null=True)),
                ('Item_description', models.TextField(null=True)),
                ('Mandatory_List', models.BooleanField(null=True)),
                ('Code', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bids',
            name='Execution_place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='Execution_plan',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='SOW',
            field=models.TextField(null=True),
        ),
    ]
