# Generated by Django 4.0.5 on 2022-07-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_bid_boq_bids_execution_place_bids_execution_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_boq',
            name='bids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.bids'),
        ),
    ]
