# Generated by Django 4.0.5 on 2022-07-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_bid_boq_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_boq',
            name='bids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.bids'),
        ),
    ]
