# Generated by Django 4.0.5 on 2022-07-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_bid_boq_bids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bid_BOQ',
        ),
    ]
